server:
  build: ./nginx/
  links:
    - server1
    - server2
    - server3
  ports:
    - "80:8080"

server1:
  build: ./
  expose:
    - "8080"

server1:
  build: ./
  expose:
    - "8080"

server1:
  build: ./
  expose:
    - "8080"
