server:
  build: ./nginx/
  links:
    - server_node1
    - server_node2
    - server_node3
  ports:
    - "80:8080"

server_node1:
  build: ./
  expose:
    - "8080"

server_node2:
  build: ./
  expose:
    - "8080"

server_node3:
  build: ./
  expose:
    - "8080"