# Use 'nginx' image.
FROM nginx

# Copy the 'package.json' needed by NPM in the current directory to the 'WORKDIR' of the container.
COPY ./nginx.json /etc/nginx/

# Expose the port 8080 which is used by the container.
EXPOSE 8080
